#!/usr/bin/env bash

set -euo pipefail

LISP=$1
BINARY=$(basename "$1" .lisp)
shift

sbcl --load "$LISP" \
    --eval "(sb-ext:save-lisp-and-die \"$BINARY\" :executable t :save-runtime-options t :toplevel '$BINARY:toplevel)" \
    "$@"
